### ISSUE TITLE
SMSVerifyCodeResult 没有包含在主项目中，github下载的zip包没有这个类

### ISSUE THREAD

**Issue by kadaseshima** [rongcloud/server-sdk-dotnet#10]
SMS.cs 方法报错，显示严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0246	未能找到类型或命名空间名“SMSVerifyCodeResult”(是否缺少 using 指令或程序集引用?)	io.rong	RongCloudServer\io\rong\methods\SMS.cs	92	活动的

**Comment by xiaoyu5062** [comment]
同样有此问题，不过如果你不需要用到短信的话，直接把这些注释了好了。

**Comment by changxiaoqiang** [comment]
已更新，新版 SDK 暂时移除对短信的支持。
