### ISSUE TITLE
SDK有点差劲啊

### ISSUE THREAD

**Issue by nextuntil** [rongcloud/server-sdk-dotnet#5]
命名空间和代码都好乱啊，大小写乱七八糟的。
然后语法也是，能用C#正常语法处理么，set/get属性什么的看的太雷人了。

**Comment by Jarven89** [comment]
您是哪个版本的 SDK

**Comment by nextuntil** [comment]
4.0的SDK，感觉就是简单从JAVA版本翻译过来敷衍的（虽然没看过JAVA SDK的代码）。

**Comment by nextuntil** [comment]
刚去看了下JAVA的SDK，C# SDK果然是简单翻译的，不过JAVA版本的也好差劲。

**Comment by Jarven89** [comment]
我们确实 是从 java 翻译过来的， 命名空间和方法空间是为了让开发者更加清楚的了解 api 的结构。

**Comment by nextuntil** [comment]
现在的写法对于C#开发者来说太不友好了，代码完全不是C#的特点，不管命名还是语法，看起来很别扭很LOW。

**Comment by LonghronShen** [comment]
I have done a .NET Core 1.0 branch with some fixes and enhancements. Some naming problems are kept as they are for compabilities to follow their code base. Welcome to join me with this branch.
https://github.com/LonghronShen/server-sdk-dotnet/tree/v4-netcore

**Comment by changxiaoqiang** [comment]
已更新，建议持续关注。
