### ISSUE TITLE
发送单聊消息的publishPrivate方法参数只能传voice类型的消息

### ISSUE THREAD

**Issue by dengyakui** [rongcloud/server-sdk-dotnet#6]
类名:
donet.io.rong.methods.message
方法签名:
 public CodeSuccessReslut publishPrivate(String fromUserId, String[] toUserId, VoiceMessage message, String pushContent, String pushData, String count, int verifyBlacklist, int isPersisted, int isCounted)

message参数只提供了VoiceMessage类型,没有其它类型消息的重载

**Comment by changxiaoqiang** [comment]
已更新，请持续关注
